# Generated by Django 6.0.3 on 2026-03-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='País')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código ISO')),
                ('flag_emoji', models.CharField(default='🏳️', max_length=10, verbose_name='Bandera')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
            },
        ),
        migrations.CreateModel(
            name='MacroVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la variable')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('source_url', models.URLField(verbose_name='URL fuente')),
                ('css_selector', models.CharField(max_length=500, verbose_name='Selector CSS')),
                ('frequency', models.CharField(choices=[('daily', 'Diaria'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral')], default='monthly', max_length=20)),
                ('is_dynamic', models.BooleanField(default=False, help_text='Marcar si la página usa JavaScript (requiere Playwright)', verbose_name='¿Página dinámica?')),
                ('unit', models.CharField(default='%', max_length=50, verbose_name='Unidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.country')),
            ],
            options={
                'verbose_name': 'Variable Macroeconómica',
                'verbose_name_plural': 'Variables Macroeconómicas',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_change', models.FloatField(verbose_name='Variación detectada (%)')),
                ('ai_verdict', models.CharField(choices=[('transitorio', 'Transitorio'), ('estructural', 'Estructural'), ('indeterminado', 'Indeterminado')], max_length=20)),
                ('justification', models.TextField(verbose_name='Justificación de la IA')),
                ('news_context', models.TextField(blank=True, verbose_name='Contexto de noticias usado')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='core.macrovariable')),
            ],
            options={
                'verbose_name': 'Análisis de IA',
                'verbose_name_plural': 'Análisis de IA',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Fecha del dato')),
                ('is_anomaly', models.BooleanField(default=False, verbose_name='¿Es anomalía?')),
                ('scraped_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de extracción')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='core.macrovariable')),
            ],
            options={
                'verbose_name': 'Dato Histórico',
                'verbose_name_plural': 'Datos Históricos',
                'ordering': ['-date'],
                'unique_together': {('variable', 'date')},
            },
        ),
    ]
