# Generated by Django 6.0.3 on 2026-03-17 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aianalysislog',
            options={'ordering': ['-analyzed_at'], 'verbose_name': 'Análisis IA', 'verbose_name_plural': 'Análisis IA'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='macrovariable',
            options={'ordering': ['country', 'name'], 'verbose_name': 'Variable Macroeconómica', 'verbose_name_plural': 'Variables Macroeconómicas'},
        ),
        migrations.AddField(
            model_name='aianalysislog',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Recomendación'),
        ),
        migrations.AddField(
            model_name='aianalysislog',
            name='risk_level',
            field=models.CharField(default='medio', max_length=10, verbose_name='Nivel de riesgo'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='ai_verdict',
            field=models.CharField(choices=[('transitorio', 'Transitorio'), ('estructural', 'Estructural'), ('indeterminado', 'Indeterminado')], default='indeterminado', max_length=20, verbose_name='Veredicto IA'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='detected_change',
            field=models.FloatField(verbose_name='Cambio detectado (%)'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='justification',
            field=models.TextField(verbose_name='Justificación'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='news_context',
            field=models.TextField(blank=True, verbose_name='Contexto de noticias'),
        ),
        migrations.AlterField(
            model_name='aianalysislog',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='core.macrovariable', verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Código ISO'),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(max_length=10, verbose_name='Bandera'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='is_anomaly',
            field=models.BooleanField(default=False, verbose_name='¿Anomalía?'),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='scraped_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicaldata',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_data', to='core.macrovariable', verbose_name='Variable'),
        ),
        migrations.AlterField(
            model_name='macrovariable',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='core.country', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='macrovariable',
            name='css_selector',
            field=models.CharField(blank=True, max_length=500, verbose_name='Selector CSS'),
        ),
        migrations.AlterField(
            model_name='macrovariable',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual'), ('quarterly', 'Trimestral')], default='monthly', max_length=20, verbose_name='Frecuencia'),
        ),
        migrations.AlterField(
            model_name='macrovariable',
            name='is_dynamic',
            field=models.BooleanField(default=False, verbose_name='Scraping dinámico'),
        ),
        migrations.AlterField(
            model_name='macrovariable',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='macrovariable',
            name='source_url',
            field=models.URLField(blank=True, verbose_name='URL fuente'),
        ),
        migrations.AlterField(
            model_name='macrovariable',
            name='unit',
            field=models.CharField(max_length=50, verbose_name='Unidad'),
        ),
    ]
